name: Product Overview
entity_id: f1C68pznmrpN1F5xFDj6d
collection_id: M-Q4pcV0qkiyJ0kiSWECl
creator_id: admin@example.com
display: table
database_id: Sample Database
dataset_query:
  "lib/type": mbql/query
  database: Sample Database
  stages:
  - "lib/type": mbql.stage/mbql
    source-table:
    - Sample Database
    - PUBLIC
    - PRODUCTS
    aggregation:
    - - count
      - "lib/uuid": 11111111-1111-1111-1111-111111111111
    - - avg
      - {}
      - - field
        - base-type: type/Float
        - - Sample Database
          - PUBLIC
          - PRODUCTS
          - PRICE
    - - avg
      - {}
      - - field
        - base-type: type/Float
        - - Sample Database
          - PUBLIC
          - PRODUCTS
          - RATING
    breakout:
    - - field
      - {}
      - - Sample Database
        - PUBLIC
        - PRODUCTS
        - CATEGORY
    order-by:
    - - desc
      - {}
      - - aggregation
        - {}
        - 11111111-1111-1111-1111-111111111111
visualization_settings: {}
serdes/meta:
- id: f1C68pznmrpN1F5xFDj6d
  label: product_overview
  model: Card
