name: Product Count
entity_id: 8kxQ2Wr7PmN5dLf3hYz9v
creator_id: admin@example.com
table_id:
- Sample Database
- PUBLIC
- PRODUCTS
definition:
  database: Sample Database
  type: query
  query:
    source-table:
    - Sample Database
    - PUBLIC
    - PRODUCTS
    aggregation:
    - - distinct
      - - field
        - - Sample Database
          - PUBLIC
          - PRODUCTS
          - ID
        - null
serdes/meta:
- id: 8kxQ2Wr7PmN5dLf3hYz9v
  label: product_count
  model: Measure
