name: Product Summary
entity_id: rT5vWxYz1aBcDeFgHiJkL
source:
  type: query
  query:
    database: Sample Database
    type: query
    query:
      source-table:
      - Sample Database
      - PUBLIC
      - PRODUCTS
      aggregation:
      - - count
      - - avg
        - - field
          - - Sample Database
            - PUBLIC
            - PRODUCTS
            - PRICE
          - base-type: type/Float
      breakout:
      - - field
        - - Sample Database
          - PUBLIC
          - PRODUCTS
          - CATEGORY
        - null
target:
  database: Sample Database
  type: table
  schema: PUBLIC
  name: product_summary
serdes/meta:
- id: rT5vWxYz1aBcDeFgHiJkL
  label: product_summary
  model: Transform
