name: Import

on:
  push:
    branches: [main]
  pull_request:

jobs:
  import-test:
    runs-on: ubuntu-latest

    env:
      MB_PREMIUM_EMBEDDING_TOKEN: ${{ secrets.MB_PREMIUM_EMBEDDING_TOKEN }}
      MB_DB_TYPE: h2
      MB_DB_FILE: /tmp/metabase

    steps:
      - uses: actions/checkout@v4

      - name: Pull Metabase
        run: docker pull metabase/metabase-enterprise:latest

      - name: Import into Metabase
        run: |
          docker run --rm \
            -e MB_PREMIUM_EMBEDDING_TOKEN \
            -e MB_DB_TYPE \
            -e MB_DB_FILE \
            -v "${{ github.workspace }}/examples/v1:/import" \
            --entrypoint java \
            metabase/metabase-enterprise:latest \
            -jar /app/metabase.jar import /import
